In [1]:
import numpy as np                              #importing numpy
import gym                                      #importing gym
import random                                      

In [2]:
env = gym.make("FrozenLake-v0")                           #creating a enviroment of frozenlake
action_space_size = env.action_space.n                    #fatching number of action
state_space_size = env.observation_space.n                #fetching number of observations (l,r,u,d)

In [21]:
#game pattren
print("""S F F F                                          
F H F H       
F F F H       
H F F G


Here S for start
G for goal
F for frozen surface (safe)
H for hole  (lose)""")   

S F F F                                          
F H F H       
F F F H       
H F F G


Here S for start
G for goal
F for frozen surface (safe)
H for hole  (lose)


In [19]:
print(action_space_size,state_space_size)               

4 16


In [4]:
q_table = np.zeros((state_space_size,action_space_size))   #creating an array for state and action carring zero value

In [5]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
num_episodes = 10000                            #number of eposides we want to run
max_steps_per_episode = 100                     #number of steps given to model under every eposide
 
learning_rate = 0.1                             #setting learning rate indication at which rate our machine will learn for better understanding
discount_rate = .99                             #

exploration_rate = 1                            #its indicating our machine sholud explore or work accoung to last updated value based omn reward
max_exploration_rate = 1                        #max rate of explroing
min_exploration_rate = 0.01                     #min rate of exploring
exploration_decay_rate = 0.001                  #its showing how our exloatation rate will decrease
#based of max and min and exploration decay rate we are going to decreasre the exploration rate and increase exploitation rate

In [8]:
rewards_all_episodes  = []                              #used to collect rewards of every episodes
for episode in range(num_episodes):                     #loop
    state = env.reset()                                 #at every episode we will set our value to start point
    
    done = False                                        #setting by default to zero
    rewards_current_episode = 0                         #used to collect the reward of current or running episode
    for step in range(max_steps_per_episode):                     #running the second loop defining each step
            exploration_rate_threshold = random.uniform(0,1)      #fetching 0 or 1 it will set that our machine chose exploration or exploitation
            if exploration_rate_threshold > exploration_rate:     
                action = np.argmax(q_table[state,:])    #here machine choose exploation means finding the best output from earlies rewards
            else:
                action = env.action_space.sample()      #here maching chosing random action to perfrom task
            
            #updating Q table
            new_state , reward , done , info = env.step(action)   #passing our action to enviroment 
            #basend on our acton step function returning new_state, float value for reward,boolen for done and dict for info
            
            # Update Q-table for Q(s,a)
            q_table[state,action] = q_table[state,action ]*(1-learning_rate)+learning_rate*(reward+discount_rate*np.max(q_table[new_state,:]))
            #this is the main formula of q-learning here we are updating our q_table for every possible state and action perform on that state

            state = new_state                  #here we are updating our updating our state returend from step function
            rewards_current_episode +=reward
            
            if done ==True:                    #if our boolen siad that its done no matter win or lose our loop will break
                break
                
    exploration_rate = min_exploration_rate+ (max_exploration_rate-min_exploration_rate)*np.exp(-exploration_decay_rate*episode)
    # ^^^ here we are decreasing the value of explorating rate  
    rewards_all_episodes.append(rewards_current_episode)   #colecting all rewards value

In [9]:
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
for r in reqards_per_thosand_episodes:
    print(count,":",str(sum(r/1000)))
    count+=1000

1000 : 0.04100000000000003
2000 : 0.19500000000000015
3000 : 0.4020000000000003
4000 : 0.5490000000000004
5000 : 0.5950000000000004
6000 : 0.6410000000000005
7000 : 0.6610000000000005
8000 : 0.6710000000000005
9000 : 0.6740000000000005
10000 : 0.7090000000000005


In [30]:
print(q_table)

[[0.58104323 0.52900305 0.52779682 0.53213348]
 [0.2227359  0.26436896 0.24627962 0.52182634]
 [0.44158646 0.42014665 0.42035078 0.48564527]
 [0.36199664 0.40095372 0.3482984  0.45264556]
 [0.59818386 0.4602776  0.48031464 0.28448503]
 [0.         0.         0.         0.        ]
 [0.17812292 0.08967009 0.2648899  0.11247258]
 [0.         0.         0.         0.        ]
 [0.39112692 0.57413149 0.36916847 0.62862632]
 [0.4251476  0.69143331 0.43395991 0.34975388]
 [0.63897002 0.43825507 0.36591811 0.22172545]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.39014788 0.48969266 0.75226653 0.39944891]
 [0.73975008 0.878356   0.74955106 0.77237422]
 [0.         0.         0.         0.        ]]
